### ISSUE TITLE
Did not receive a message to download en_core_web_sm when using default spacy harness locally

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/nlptest#254]
I should receive a message to download en_core_web_sm if i don't have it and tried to use the default spacy harness.
`python -m spacy download en_core_web_sm`

Instead i got this error:
```
>>> h = Harness(model="en_core_web_sm", hub="spacy")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nlptest/nlptest/nlptest.py", line 80, in __init__
    self.model = ModelFactory.load_model(path=model, task=task, hub=hub)
  File "/nlptest/nlptest/modelhandler/modelhandler.py", line 112, in load_model
    model_class = modelhandler_module.PretrainedModelForNER.load_model(path)
  File "/nlptest/nlptest/modelhandler/spacy_modelhandler.py", line 30, in load_model
    return spacy.load(path)
  File "/opt/anaconda3/lib/python3.8/site-packages/spacy/__init__.py", line 54, in load
    return util.load_model(
  File "opt/anaconda3/lib/python3.8/site-packages/spacy/util.py", line 449, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
```

**Comment by chakravarthik27** [comment]
@luca-martial 
the output should be like this:
`ValueError: python -m spacy download en_core_web_lg`
or 
`OSError: python -m spacy download en_core_web_lg`

**Comment by luca-martial** [comment]
> @luca-martial the output should be like this: `ValueError: python -m spacy download en_core_web_lg` or `OSError: python -m spacy download en_core_web_lg`
```
OSError: Please download en_core_web_sm from spaCy to use this model: 
python -m download spacy en_core_web_sm
```
